# -*- coding: utf-8 -*-
"""Salinan dari employee-attrition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLxCFSfnBZL_X3i0cdMM-9qOJNdRgLH1
"""

!pip install shap

!pip install pycaret[analysis]

!pip install pycaret

import pandas as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pycaret.classification import *


df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/employee/employee_data.csv')

df

df.isnull().sum()

df = df.dropna()
df.isnull().sum()

df.shape

default_counts = df['Attrition'].value_counts()
default_counts

clf1 = setup(data = df, target = 'Attrition', fix_imbalance=True)

best_model = compare_models()

plot_model(best_model, plot = 'confusion_matrix')

interpret_model(best_model)

# Visualisasi hubungan antara Gender dan Attrition
plt.figure(figsize=(10, 6))
sns.countplot(x='JobLevel', hue='Attrition', data=df)
plt.title('Attrition by Job Level')
plt.show()

# Visualisasi hubungan antara Gender dan Attrition
plt.figure(figsize=(10, 6))
sns.countplot(x='StockOptionLevel', hue='Attrition', data=df)
plt.title('Attrition by Stock Option Level')
plt.show()

# Visualisasi hubungan antara Gender dan Attrition
plt.figure(figsize=(10, 6))
sns.countplot(x='EnvironmentSatisfaction', hue='Attrition', data=df)
plt.title('Attrition by Environment Satisfaction')
plt.show()

# Visualisasi hubungan antara Gender dan Attrition
plt.figure(figsize=(10, 6))
sns.countplot(x='BusinessTravel', hue='Attrition', data=df)
plt.title('Attrition by Environment Satisfaction')
plt.show()

